site_name: Bits Please Technologies N.V. - Dev Docs
nav:
  - Home: index.md
  - Internal Pipelines:
      - Cold Calls: internal-pipelines/cold-calls.md
      - Cold Emails: internal-pipelines/cold-emails.md
  - Project Starters:
      - NextJS Starter: project-setup/nextjs-starter.md
      - NestJS Starter: project-setup/nestjs-starter.md
  - Project Documentation:
    - Speed Money Wise: project-documentation/speed-money-wise/index.md
theme:
  name: material
  logo: images/logo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
